language: node_js
node_js:
  - "10"
cache:
  directories:
    - ~/.npm
env:
  global:
    - TRUNK_BRANCH="master"
    - secure: "KErxu2spmirmB4Ik2pyb4buCCnM9E53JTrhUP3Gig2lxPNq0ngGkHQScr64QtSzmPt9r9SGpq/mgwxKq/8UACg1GT52X06c1uKFazGiW2rOrluETgpqsfHt2Xf7GIX+ZY2Cc7kqIbTZeDrYdaC8YYXlOn21z0hynvZv8LNOSrRvMjFZgaAyAEhtdadEZYW3TjmOtfRF1BtDlb/4/sPcNofVB21UiS5C2CeJIfm4yDVPWiYdH5WQkwxJAzUH5Z2h7dERrBE8oac3fsq9aUEqfmkBq5aght6ZCD8A7CFyngQPxY72tUtKzRGgDDGDiQnoM9SnFqdkas1lmNY/A5/KNu0faKsnVOWZMSVDo9LBnbpYK80REjG30F7VuND+wYFOqNMt0ZCXVJ1BlUtfoIpKsUJel63ka/eUaF91pAVgCD1xv2HIqnApjmu5wuR6ENa3mOMh6nL+wCcZBEAAcPlIZCzia2eX2/W1UJ36CMZdlV5J2oBNqQgDGwQcen1Y4uLh1l9N7oil/5ym5XD7u00LUoUMB7BvVKpVRfd3ki/ncSwZwRjmsiZoNK0k3Y5XX97V93igbnI2F78OGDJdGdinI+S/XGN/BJ42MZuf1HDoYL5sO0Lsg65Sk6mPzW2xf/D1FimgsCfvcnH9AYSoOdPp//Ovk5k+vOVwqVrm4OYoiOkg="
    - secure: "qVUr5M3d++aoHGk70nB3esSAEKM576TAZ1cWodRQ+ncxtKYuBQqvpLHllmSBZaMPO4+9nVRJbW5MwaNvtmTnvDLZmaxbeBsXL/L6CLo/yd5/gyVQr0/yqwz0fxEGJ7ebpzPw9Pdz3JYAyMsm88YLgl76cqYsZVbCwEQSynigyCyYzIx7VWIQDNvBt3uJjHW8tfXEtscvygvTEuj8c32DmqrsRSoDL5jY5h2KVd9l+4ERkWJQP1mxcP15Rb6qH/PuMpNTqIvr1MAjQ98W9JR57zdyGG6XQNKNLmNG5k+jVS1gXhObaEJv6Z2XSeGvJmHjpgZQT14tBLKqhIGf0r0Z2K+Tq1d1X3sZUy/y+f85ZXqHLxjuxWFDS73QC29iFVFmYvDTWOHlxiZO4T9Pk0NHMFTObaX6JYOAu5Q1WLdePuWcpYF9Wa+rYJazdSo8/K/6B6PIGMIfrHNltc7pV7jyTn8P08F9bqPPq2RyqYvEIv/P6gXJqxKeXPwmxPn9Y8+GHPRqpvDi/Dg+lHC6/2XRS6m7xXR4oqR1HyJLD5BLAtaGGjOKtpJUIQVYrX22qHtB0D3EMZh6vf+w87bDRsWH+9Usp/RonTu0aqEKTDC0zHYLSLhfNmMnCfX5P1bVL/UFza8IxVsOZCgBPWPUbH49p49iHBspzncCXdObGXbQDZQ="
install:
  - npm ci
script: skip
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: release
      if: branch = env(TRUNK_BRANCH) AND type = push
      script:
        - ./ci/prepare-release.sh || travis_terminate 1
        - npm run release || travis_terminate 1
        - git push --follow-tags origin $TRAVIS_BRANCH || travis_terminate 1
        - npm run github-release || travis_terminate 1
        - npm publish || travis_terminate 1
