name: Ehealth Schema

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


env:
  SLACK_CHANNEL: "#ci"
  SLACK_URL: ${{secrets.SLACK_URL}}
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install
      - run: npm test
      - name: lint
        run: npm run lint
      - name: release
        run: |
          ./ci/prepare-release.sh
          npm run release 
          git push --follow-tags 
          echo $GITHUB_TOKEN
          npm run github-release 
          npm publish 

      # - name: On failure
      #   if: failure()
      #   run: |
      #     curl -X POST --data-urlencode "payload={\"channel\": \"$SLACK_CHANNEL\",\"username\": \"Github Actions\",\"icon_emoji\": \":github:\",\"attachments\": [{\"color\": \"danger\",\"fields\": [{\"title\": \"Build failed\",\"value\": \"for <https://github.com/edenlabllc/ehealth.charts/actions|ehealth.charts/${GITHUB_REF##*/}> (<https://github.com/edenlabllc/ehealth.charts/commit/$GITHUB_SHA|${GITHUB_SHA:0:7}>) by *$GITHUB_ACTOR*\",\"short\": false}]}]}" $SLACK_URL
      # - name: On success
      #   if: success()
      #   run: |
      #     curl -X POST --data-urlencode "payload={\"channel\": \"$SLACK_CHANNEL\",\"username\": \"Github Actions\",\"icon_emoji\": \":github:\",\"attachments\": [{\"color\": \"good\",\"fields\": [{\"title\": \"Build success\",\"value\": \"for <https://github.com/edenlabllc/ehealth.charts/actions|ehealth.charts/${GITHUB_REF##*/}> (<https://github.com/edenlabllc/ehealth.charts/commit/$GITHUB_SHA|${GITHUB_SHA:0:7}>) by *$GITHUB_ACTOR*\",\"short\": false}]}]}" $SLACK_URL
      # - name: Skipped
      #   if: "contains(github.event.head_commit.message, '[ci skip]')"
      #   run: |
      #     curl -X POST --data-urlencode "payload={\"channel\": \"$SLACK_CHANNEL\",\"username\": \"Github Actions\",\"icon_emoji\": \":github:\",\"attachments\": [{\"color\": \"warning\",\"fields\": [{\"title\": \"Build skipped\",\"value\"