name: Ehealth Schema

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


env:
  SLACK_CHANNEL: "#ci"
  SLACK_URL: ${{secrets.SLACK_URL}}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 10.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test


      - name: lint
        run: npm run lint
      - name: release
        run: |
          source ./ci/prepare-release.sh || travis_terminate 1
          npm run release || travis_terminate 1
          git push --follow-tags origin $TRAVIS_BRANCH || travis_terminate 1
          npm run github-release || travis_terminate 1
          npm publish || travis_terminate 1

      # - name: On failure
      #   if: failure()
      #   run: |
      #     curl -X POST --data-urlencode "payload={\"channel\": \"$SLACK_CHANNEL\",\"username\": \"Github Actions\",\"icon_emoji\": \":github:\",\"attachments\": [{\"color\": \"danger\",\"fields\": [{\"title\": \"Build failed\",\"value\": \"for <https://github.com/edenlabllc/ehealth.charts/actions|ehealth.charts/${GITHUB_REF##*/}> (<https://github.com/edenlabllc/ehealth.charts/commit/$GITHUB_SHA|${GITHUB_SHA:0:7}>) by *$GITHUB_ACTOR*\",\"short\": false}]}]}" $SLACK_URL
      # - name: On success
      #   if: success()
      #   run: |
      #     curl -X POST --data-urlencode "payload={\"channel\": \"$SLACK_CHANNEL\",\"username\": \"Github Actions\",\"icon_emoji\": \":github:\",\"attachments\": [{\"color\": \"good\",\"fields\": [{\"title\": \"Build success\",\"value\": \"for <https://github.com/edenlabllc/ehealth.charts/actions|ehealth.charts/${GITHUB_REF##*/}> (<https://github.com/edenlabllc/ehealth.charts/commit/$GITHUB_SHA|${GITHUB_SHA:0:7}>) by *$GITHUB_ACTOR*\",\"short\": false}]}]}" $SLACK_URL
      # - name: Skipped
      #   if: "contains(github.event.head_commit.message, '[ci skip]')"
      #   run: |
      #     curl -X POST --data-urlencode "payload={\"channel\": \"$SLACK_CHANNEL\",\"username\": \"Github Actions\",\"icon_emoji\": \":github:\",\"attachments\": [{\"color\": \"warning\",\"fields\": [{\"title\": \"Build skipped\",\"value\"