name: Ehealth Schema PR

on:
  pull_request:
    branches: [ master ]


env:
  SLACK_CHANNEL: "#ci"
  SLACK_URL: ${{secrets.SLACK_URL}}
  #CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ secrets.CONVENTIONAL_GITHUB_RELEASER_TOKEN }}
  CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.GITHUB_TOKEN}}
  DEBUG: conventional-github-releaser
  #NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install
      - name: lint
        run: npm run lint
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4